### ISSUE TITLE
sampling work

### ISSUE THREAD

**Issue by binxuan98** [sndnyang/iDDPM#1]
Thank you very much for your work. I have two questions; please help me.
(i) Is there any plan to separate the sampling work? I found that you are now implementing sampling in each iteration during the training process.
(ii) How to use open ai's pre-trained models to sample in your code.
The trouble you again.

**Comment by sndnyang** [comment]
2) you mean `python iddpm_eval.py --eval gen --resume path/your/checkpoint.pth --gpu-id 0` ?  Of course, you need to check the model's configurations in  iddpm/script_util.py to load the model.

1) in most cases, the TODO list is a never-do list.

**Comment by binxuan98** [comment]
Thanks for your reply, I will try.
