### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by MaoFuyou** [sndnyang/iDDPM#5]
![image](https://github.com/user-attachments/assets/4b4c4036-0f23-44b3-b6fe-9d566ef63473)
您好 在运行iddpm_main.py的时候 一直卡在这个地方 不动是怎么回事 但是GPU占用还一直有

**Comment by sndnyang** [comment]
这就是VPN下载问题——你可以按这两个位置，下载下来 放到那个位置 就OK。
